version: '3.0'

services:
  node-app:
    build:
      context: .
    container_name: node-app
    entrypoint: dockerize -wait tcp://node-db:3306 -timeout 20s node index.js
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - minha-rede-node-backend
    tty: true
    depends_on:
      - node-db

  node-proxy:
    image: nginx
    container_name: node-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - minha-rede-node-backend
      - minha-rede-node-frontend
    tty: true
    depends_on:
      - node-app

  node-db:
    image: mysql
    command: --innodb_use_native_aio=0
    container_name: node-db
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=node_database
    networks:
      - minha-rede-node-backend
    volumes:
      - mysql-vol:/var/lib/mysql
      - ./database/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

networks:
  minha-rede-node-backend:
    internal: true
  minha-rede-node-frontend:
    internal: false
volumes:
  node-app-vol:
  mysql-vol:
